name: Server CI

on:
  workflow_call:
    inputs:
      working_directory:
        description: "The working directory of the caller workflow repository"
        default: "."
        type: string

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: go mod download
      - name: Run Tests
        run: go test ./...
        env:
          CI: true
          CONFIG: ${{ secrets.CONFIG }}
